CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:Q/X+0JMyGTkBtN7ikkohnl71ZAm6b+2sv6zcn/Sv2/6DdxE20pdmq+BiZ4+LWYcxxTZ25T0=,iv:HVPH3v5ENCeAK4j1GdUqvy88Lgj3Hdl+d4Hy4JQsfBQ=,tag:6dFgRgd7//KnIZ8uPgb/CA==,type:str]
KOMODOC_LABEL: ENC[AES256_GCM,data:Cro6GxNvQg==,iv:/GMEqsZgu7lCHtvgUjsCSgJ16G4uVAw6y0DUfP37vNY=,tag:1yleZi12co4go1STOX0nbQ==,type:str]
KOMODOC_ENDPOINT: ENC[AES256_GCM,data:QImZfE4HCwMtRBabTERVfiRSSsks,iv:puAXd7rgWApqVcoBd2ky29Z5F4A6BNfzno/fp4CtAKs=,tag:+wAs1t9v3UnP8jL5J40YuQ==,type:str]
KOMODOC_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:HsQ8koPv3HE+6R1B5gTaJpqd7FM=,iv:cphZhrLipIzBU2dd7Z5HQkXqG5ujinte0CL9XmCNCEA=,tag:d+UOU7HUHRQs2J8yPNy0cg==,type:str]
KOMODOC_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:Ghgi4apf51sls+dD9zQqes3AJD+SOg/tRs1Iw1qTS7A3tWJtH2jFmQ==,iv:5uM9S+Unlnz+jUyo8NEf/e+IG3bF6NCNq8sEzcXpanI=,tag:mogbamOFn5gP4DozgvLCVg==,type:str]
KOMODOC_ENDPOINT_SANDBOX: ENC[AES256_GCM,data:gBvS4d6f9c6mGxpNKkAiFcPKHMJVLuu2YHYDoaMv7QlDmOeT6uTDM2bOvuvw/A==,iv:TmNGmILJCR7W9EnRixb+C2CHDTC5HKih+tNrVrDQaYE=,tag:gRrGEgKUHl48LHW4AKBrTg==,type:str]
KOMODOC_GITHUB_CLIENT_ID_SANDBOX: ENC[AES256_GCM,data:IuDT/LAMbwOuvfKPK1S8ye/uXRQ=,iv:S9fQoTBKBvxXBjeVvI0vtckiOXxqditFjLdR0qDkQ44=,tag:wSPtdIZacI7I+IfPPGGDSQ==,type:str]
KOMODOC_GITHUB_CLIENT_SECRET_SANDBOX: ENC[AES256_GCM,data:MJeDYHrpIBlkz32yJlyYd4lD63xjYOdj92Eeb9Ljy0k3cljGOkzYfw==,iv:YEviEfrQffP2YMAxFTb6aF3VPdryXUiIqo7YgT1HDTI=,tag:luBgvRt8SKGXpww4BZDAng==,type:str]
sops:
    lastmodified: "2026-09-03T12:22:48Z"
    mac: ENC[AES256_GCM,data:h7acYVjsvH47oxjrHxFNxYip9Jv8iGtY5RoXsMlpUJZ4SSUeTeViwWFVpR717KeYJKTD/9/RNsy9bWf3k2ehp2duH6ELhP5Fg2w7e+WP8sq2fgDoS4sChWhvXcaN2IUgkuTb83lywOk3U0YPIDY3ruTpsf8Z35q/252J+sw3L14=,iv:YKHquInq/TdosYJYICJzSWZ3Nmz/6j2gEvkx/gOKbS0=,tag:Ff/uOesJqqrIXW13Zqcz4g==,type:str]
    pgp:
        - created_at: "2026-09-03T12:08:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA+YQb2amrEajAQgAk4HAtZkhPYX9qp3vMYmtoFBgNrwgqClwnXMxEjtfH1pM
            Z+/FUfWozItEiLfSSvqD84fDniKzL3RTwYRyNCR7JX63VwlpLJWr5BMUou9FuanO
            imwHDgw1XjEr85C7Rxq2XOxjhzkdScuE2qySLTis2OPpSCmeQPlY2IA+HmrrQWff
            056jAWtmP7CN1h805MHT1grMal4ZDbvwvntdguUb+WcWFtbInwZtSVTAD7cXlTBR
            n/m6dm9tpXtVg+6gjz6bRPIrqLsUFb0oKpwyZQgW63aR37tvGIN6HghdrP6H7QeV
            Eu0of+Aoz/SJh0TIgoi2ucj/Yxp9w4gXwApRFfPmYtJeAcxecZdgADgFP9Wo3Ser
            Ek8j0JDNwsrVd7/q+Hgwqhr063+xcKSkyhbwPZTy8Vv73zNp1ykNBGS5XqsFY/MP
            roVL4h9rtOi8T1TDvNxBIHEcH7fDZIYc3u95D+HqkA==
            =h0HA
            -----END PGP MESSAGE-----
          fp: B84CF1587A9E41A4C8B05990831F3F76EE332BF2
    unencrypted_suffix: _unencrypted
    version: 3.13.3
